models:
  - display_name: Gemma 3 1B
    model_id: gemma3:1b
    base_url: http://localhost:11434
    local: true
  - display_name: Qwen2.5 Coder 0.5B
    model_id: qwen2.5-coder:0.5b
    base_url: http://localhost:11434
    local: true
  - display_name: Llama 3.2 3B
    model_id: llama3.2:3b
    base_url: http://localhost:11434
    local: true
