[project]
name = "union-llm-serving"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.8"
dependencies = [
    "huggingface-hub>=0.30.2",
    "mashumaro[yaml]>=3.15",
    "openai>=1.75.0",
    "streamlit>=1.44.1",
    "union>=0.1.173",
]
